language: go 
sudo: required
env:
  global:
    - BASE_DIR=/home/travis/gopath/src/github.com/palletone/go-palletone
    - ALL_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/node/log/all.log
    - GAS_TOKEN_ALL_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/GasToken/node/log/all.log
    - BDD_LOG_PATH=/home/travis/gopath/src/github.com/palletone/go-palletone/bdd/logs
    - CREATE_TRANS_DIR=createTrans
    - CONTRACT20_DIR=crt20Contract
    - SEQENCE721_DIR=crt721Seqence
    - UDID721_DIR=crt721UDID
    - VOTECONTRACT_DIR=voteContract
    - MULTIPLE_DIR=zMulti-node
    - DIGITAL_IDENTITY_DIR=DigitalIdentityCert
    - DEPOSIT_DIR=deposit
    - GAS_TOKEN_DIR=gasToken
    - MEDIATOR_VOTE_DIR=meidatorvote
    - LOG_NAME=log.html
    - REPORT_NAME=report.html
##########  control testcase  ##############
    - IS_RUN_DEPOSIT=true
    - IS_RUN_TESTCONTRACTCASES=true
    - IS_RUN_CREATE_TRANS=true
    - IS_RUN_20CONTRACT=true
    - IS_RUN_721SEQENCE=true
    - IS_RUN_721UDID=true
    - IS_RUN_MULTIPLE=true
    - IS_RUN_DIGITAL=true
    - IS_RUN_VOTE=true
    - IS_RUN_GASTOKEN=true
    - IS_RUN_MEDIATOR_VOTE=true
    - GO111MODULE=on
    - IS_UPLOAD=true
#    - 'SFTP_KEY=[base64-encoded-rsa-key]'
matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.10.x
      env: UT
      script:
        - go get github.com/mattn/goveralls
        - go build ./cmd/gptn
        - make gptn
        - go test ./...
        # - $GOPATH/bin/goveralls -service=travis-ci
    - os: osx
      go: 1.12.x
      env: UT
      install:
        - brew install inetutils
        - brew install expect
        - chmod +x ./bdd/macUpload2Ftp.sh
      script:
        - go build ./cmd/gptn
        - make gptn
        - go test ./...
        - tar czvf gptn-mac.tar.gz ./gptn
        - ./bdd/macUpload2Ftp.sh ${FTP_PWD} ${TRAVIS_BRANCH}
    
before_install:
    - go get -u github.com/palletone/adaptor
    - go get -u github.com/palletone/btc-adaptor
    - go get -u github.com/palletone/eth-adaptor
    - source ./build/goget_by_version.sh
    #- source ./gomockgen.sh
    
addons:
  apt:
    update: true

notifications:
  email:
    recipients:
      - travisreport@163.com
    on_success: always # default: change
    on_failure: always