os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\palletone\go-palletone
version: "{branch}.{build}"
environment:
  global:
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
    # - GETH_ARCH: 386
    #   MSYS2_ARCH: i686
    #   MSYS2_BITS: 32
    #   MSYSTEM: MINGW32
    #   PATH: C:\msys64\mingw32\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.10.8.windows-%GETH_ARCH%.zip
  - 7z x go1.10.8.windows-%GETH_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version
before_build:
  - go get -u github.com/palletone/adaptor
  - go get -u github.com/palletone/btc-adaptor
  - go get -u github.com/palletone/eth-adaptor
  - go get -u github.com/palletone/digital-identity/...
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen
build_script:
  - C:\gopath\bin\mockgen.exe -source=".\dag\interface.go" -destination=".\dag\ag_mock.go" -package="dag" -self_package="github.com/palletone/go-palletone/dag"
  - go run build\ci.go install

after_build:
  - go run build\ci.go archive -type zip -signer WINDOWS_SIGNING_KEY -upload ""
  # - go run build\ci.go nsis -signer WINDOWS_SIGNING_KEY -upload ""

test_script:
   - set CGO_ENABLED=1
   - go test ./...
