[Ptn]
NetworkId = 1
SyncMode = "full"
LightPeers = 100
DatabaseCache = 768
GasPrice = 1000000
EnablePreimageRecording = false

[Ptn.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Ptn.GPO]
Blocks = 20
Percentile = 60

[Ptn.Dag]
DbPath = "./leveldb"
DbName = "palletone"
DbCache = 0
DbHandles = 0
CacheSource = ""
RedisAddr = ""
RedisPwd = ""
RedisPrefix = ""
RedisDb = 0

[Ptn.Log]
OutputPaths = ["stdout"]
ErrorOutputPaths = ["stderr"]
LoggerLvl = "DEBUG"
Encoding = "console"
Development = true

[Ptn.MediatorPlugin]
EnableStaleProduction = false

[Node]
DataDir = "C:\\Users\\Albert\\AppData\\Roaming\\PalletOne"
IPCPath = "gptn.ipc"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000

[MediatorPlugin]
EnableStaleProduction = false

[Log]
OutputPaths = ["stdout"]
ErrorOutputPaths = ["stderr"]
LoggerLvl = "DEBUG"
Encoding = "console"
Development = true

[Dag]
DbPath = "./leveldb"
DbName = "palletone"
DbCache = 0
DbHandles = 0
CacheSource = ""
RedisAddr = ""
RedisPwd = ""
RedisPrefix = ""
RedisDb = 0

[P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Ada]
Ada1 = "Ada1"
Ada2 = "Ada2"
